<a href="https://colab.research.google.com/github/Anichan55/Churn_Analysis/blob/main/Churn_Analysis_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the Libraries**

In [180]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [181]:
tf.__version__

'2.6.0'

# **Data Preprocessing**

### Importing the Dataset

In [182]:
dataset = pd.read_csv('churnTrain.csv')
dataset=dataset.drop(columns='Phone_No')
X = dataset.iloc[:,2:-1].values
Y = dataset.iloc[:,-1].values

In [183]:
dataset.columns

Index(['State', 'Account_Length', 'Area_Code', 'International_Plan',
       'Voice_Mail_Plan', 'No_Vmail_Messages', 'Total_Day_minutes',
       'Total_Day_Calls', 'Total_Day_charge', 'Total_Eve_Minutes',
       'Total_Eve_Calls', 'Total_Eve_Charge', 'Total_Night_Minutes',
       'Total_Night_Calls', 'Total_Night_Charge', 'Total_Intl_Minutes',
       'Total_Intl_Calls', 'Total_Intl_Charge', 'No_CS_Calls', 'Churn'],
      dtype='object')

In [184]:
X

array([[415, ' no', ' yes', ..., 3, 2.7, 1],
       [415, ' no', ' yes', ..., 3, 3.7, 1],
       [415, ' no', ' no', ..., 5, 3.29, 0],
       ...,
       [510, ' no', ' no', ..., 6, 3.81, 2],
       [510, ' yes', ' no', ..., 10, 1.35, 2],
       [415, ' no', ' yes', ..., 4, 3.7, 0]], dtype=object)

In [185]:
Y

array([False, False, False, ..., False, False, False])

### One Hot Encoding the Area Code column

In [186]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

### Label Encoding the "Internation Plan" and "Voice Mail" Plan column

In [187]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,3] = le.fit_transform(X[:,3])
X[:,4] = le.fit_transform(X[:,4])

## Label Encoding the dependent variable Y

In [188]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)


# **Splitting the dataset into the Training set and Test set**


In [189]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [190]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Building the** **ANN**

In [191]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# **Training the ANN**

In [192]:
ann.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

In [193]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
84/84 [==============================] - 1s 1ms/step - loss: 0.2050 - accuracy: 0.7802
Epoch 2/100
84/84 [==============================] - 0s 2ms/step - loss: 0.1632 - accuracy: 0.8515
Epoch 3/100
84/84 [==============================] - 0s 2ms/step - loss: 0.1384 - accuracy: 0.8518
Epoch 4/100
84/84 [==============================] - 0s 2ms/step - loss: 0.1253 - accuracy: 0.8518
Epoch 5/100
84/84 [==============================] - 0s 2ms/step - loss: 0.1174 - accuracy: 0.8522
Epoch 6/100
84/84 [==============================] - 0s 2ms/step - loss: 0.1111 - accuracy: 0.8608
Epoch 7/100
84/84 [==============================] - 0s 2ms/step - loss: 0.1052 - accuracy: 0.8792
Epoch 8/100
84/84 [==============================] - 0s 2ms/step - loss: 0.0997 - accuracy: 0.8867
Epoch 9/100
84/84 [==============================] - 0s 2ms/step - loss: 0.0948 - accuracy: 0.8871
Epoch 10/100
84/84 [==============================] - 0s 1ms/step - loss: 0.0905 - accuracy: 0.8905
Epoch 11/

## **Predicting the results of the test set of ChurnTrain**

In [194]:
X_test

array([[-0.58225906,  1.01435661, -0.58341413, ...,  0.21418988,
        -0.33633574, -1.17967998],
       [-0.58225906, -0.98584659,  1.71404831, ..., -0.60566687,
        -0.08616319,  0.33819011],
       [-0.58225906, -0.98584659,  1.71404831, ..., -0.19573849,
         0.8091912 ,  1.09712515],
       ...,
       [-0.58225906,  1.01435661, -0.58341413, ..., -0.60566687,
         0.55901865, -0.42074493],
       [ 1.71744858, -0.98584659, -0.58341413, ..., -1.42552363,
        -0.83668084, -0.42074493],
       [ 1.71744858, -0.98584659, -0.58341413, ..., -0.19573849,
        -0.29683481,  1.09712515]])

In [195]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [196]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[557  22]
 [ 24  64]]


0.9310344827586207

## **Working on ChrunTest Dataset**

In [197]:
dataset = pd.read_csv('churnTest.csv')
dataset=dataset.drop(columns='Phone_No')
#X = dataset.iloc[:,2:].values


# Working with Nan values in the dataset

In [198]:
dataset.isna().sum()

State                   0
Account_Length          1
Area_Code               1
International_Plan      5
Voice_Mail_Plan         4
No_Vmail_Messages       0
Total_Day_minutes       7
Total_Day_Calls         4
Total_Day_charge       11
Total_Eve_Minutes      11
Total_Eve_Calls         4
Total_Eve_Charge        5
Total_Night_Minutes    11
Total_Night_Calls       6
Total_Night_Charge      4
Total_Intl_Minutes      3
Total_Intl_Calls        5
Total_Intl_Charge       0
No_CS_Calls             0
dtype: int64

## Dropping the row with Area code NaN

In [199]:
dataset.dropna(subset = ["Area_Code"], inplace=True)

## Filling NaN values in 'Voice Mail Plan' and 'International Plan' with 'no'

In [200]:
dataset['Voice_Mail_Plan'] = dataset['Voice_Mail_Plan'].fillna('no')
dataset['International_Plan'] = dataset['International_Plan'].fillna('no')


In [201]:
X = dataset.iloc[:,2:].values

### **One Hot Encoding the Area Code column and Label Encoding the "Internation Plan" and "Voice Mail" Plan column**

In [202]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [203]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,3] = le.fit_transform(X[:,3])
X[:,4] = le.fit_transform(X[:,4])

# Feature Scaling

In [204]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

# Predicting Churn Column of ChurnTest Dataset

In [205]:
y_pred = ann.predict(X)
y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [206]:
y_pred

df = pd.DataFrame(data=y_pred, columns=['Churn'])

In [207]:
frames = [dataset, df]

result = pd.concat(frames,axis=1)

In [208]:
result.to_csv('Result.csv')